export interface CountryCurrencyPreset {
  id: string;
  name: string;
  flag: string;
  currencyCode: string;
  currencySymbol: string;
  currencyName: string;
  currencyPosition: 'before' | 'after';
  numberFormat: 'standard' | 'indian';
  defaultTaxRate: number;
  taxName: string;
  hasUpiSupport?: boolean;
}

export const COUNTRY_CURRENCY_PRESETS: CountryCurrencyPreset[] = [
  {
    id: 'IN',
    name: 'India',
    flag: '🇮🇳',
    currencyCode: 'INR',
    currencySymbol: '₹',
    currencyName: 'Indian Rupee (INR)',
    currencyPosition: 'before',
    numberFormat: 'indian',
    defaultTaxRate: 18,
    taxName: 'GST',
    hasUpiSupport: true,
  },
  {
    id: 'US',
    name: 'United States',
    flag: '🇺🇸',
    currencyCode: 'USD',
    currencySymbol: '$',
    currencyName: 'US Dollar (USD)',
    currencyPosition: 'before',
    numberFormat: 'standard',
    defaultTaxRate: 8.5,
    taxName: 'Sales Tax',
  },
  {
    id: 'GB',
    name: 'United Kingdom',
    flag: '🇬🇧',
    currencyCode: 'GBP',
    currencySymbol: '£',
    currencyName: 'British Pound (GBP)',
    currencyPosition: 'before',
    numberFormat: 'standard',
    defaultTaxRate: 20,
    taxName: 'VAT',
  },
  {
    id: 'EU',
    name: 'European Union',
    flag: '🇪🇺',
    currencyCode: 'EUR',
    currencySymbol: '€',
    currencyName: 'Euro (EUR)',
    currencyPosition: 'before',
    numberFormat: 'standard',
    defaultTaxRate: 21,
    taxName: 'VAT',
  },
  {
    id: 'AE',
    name: 'United Arab Emirates',
    flag: '🇦🇪',
    currencyCode: 'AED',
    currencySymbol: 'AED ',
    currencyName: 'UAE Dirham (AED)',
    currencyPosition: 'before',
    numberFormat: 'standard',
    defaultTaxRate: 5,
    taxName: 'VAT',
  },
  {
    id: 'SA',
    name: 'Saudi Arabia',
    flag: '🇸🇦',
    currencyCode: 'SAR',
    currencySymbol: 'SAR ',
    currencyName: 'Saudi Riyal (SAR)',
    currencyPosition: 'before',
    numberFormat: 'standard',
    defaultTaxRate: 15,
    taxName: 'VAT',
  },
  {
    id: 'CA',
    name: 'Canada',
    flag: '🇨🇦',
    currencyCode: 'CAD',
    currencySymbol: 'CA$',
    currencyName: 'Canadian Dollar (CAD)',
    currencyPosition: 'before',
    numberFormat: 'standard',
    defaultTaxRate: 13,
    taxName: 'HST/GST',
  },
  {
    id: 'AU',
    name: 'Australia',
    flag: '🇦🇺',
    currencyCode: 'AUD',
    currencySymbol: 'A$',
    currencyName: 'Australian Dollar (AUD)',
    currencyPosition: 'before',
    numberFormat: 'standard',
    defaultTaxRate: 10,
    taxName: 'GST',
  },
  {
    id: 'SG',
    name: 'Singapore',
    flag: '🇸🇬',
    currencyCode: 'SGD',
    currencySymbol: 'S$',
    currencyName: 'Singapore Dollar (SGD)',
    currencyPosition: 'before',
    numberFormat: 'standard',
    defaultTaxRate: 9,
    taxName: 'GST',
  },
  {
    id: 'BD',
    name: 'Bangladesh',
    flag: '🇧🇩',
    currencyCode: 'BDT',
    currencySymbol: '৳',
    currencyName: 'Bangladeshi Taka (BDT)',
    currencyPosition: 'before',
    numberFormat: 'indian',
    defaultTaxRate: 15,
    taxName: 'VAT',
  },
  {
    id: 'PK',
    name: 'Pakistan',
    flag: '🇵🇰',
    currencyCode: 'PKR',
    currencySymbol: '₨',
    currencyName: 'Pakistani Rupee (PKR)',
    currencyPosition: 'before',
    numberFormat: 'indian',
    defaultTaxRate: 18,
    taxName: 'Sales Tax',
  },
  {
    id: 'NP',
    name: 'Nepal',
    flag: '🇳🇵',
    currencyCode: 'NPR',
    currencySymbol: '₨',
    currencyName: 'Nepalese Rupee (NPR)',
    currencyPosition: 'before',
    numberFormat: 'indian',
    defaultTaxRate: 13,
    taxName: 'VAT',
  },
  {
    id: 'LK',
    name: 'Sri Lanka',
    flag: '🇱🇰',
    currencyCode: 'LKR',
    currencySymbol: 'Rs ',
    currencyName: 'Sri Lankan Rupee (LKR)',
    currencyPosition: 'before',
    numberFormat: 'standard',
    defaultTaxRate: 18,
    taxName: 'VAT',
  },
  {
    id: 'JP',
    name: 'Japan',
    flag: '🇯🇵',
    currencyCode: 'JPY',
    currencySymbol: '¥',
    currencyName: 'Japanese Yen (JPY)',
    currencyPosition: 'before',
    numberFormat: 'standard',
    defaultTaxRate: 10,
    taxName: 'Tax',
  },
  {
    id: 'PH',
    name: 'Philippines',
    flag: '🇵🇭',
    currencyCode: 'PHP',
    currencySymbol: '₱',
    currencyName: 'Philippine Peso (PHP)',
    currencyPosition: 'before',
    numberFormat: 'standard',
    defaultTaxRate: 12,
    taxName: 'VAT',
  },
  {
    id: 'MY',
    name: 'Malaysia',
    flag: '🇲🇾',
    currencyCode: 'MYR',
    currencySymbol: 'RM ',
    currencyName: 'Malaysian Ringgit (MYR)',
    currencyPosition: 'before',
    numberFormat: 'standard',
    defaultTaxRate: 6,
    taxName: 'SST',
  },
  {
    id: 'ZA',
    name: 'South Africa',
    flag: '🇿🇦',
    currencyCode: 'ZAR',
    currencySymbol: 'R ',
    currencyName: 'South African Rand (ZAR)',
    currencyPosition: 'before',
    numberFormat: 'standard',
    defaultTaxRate: 15,
    taxName: 'VAT',
  },
  {
    id: 'NG',
    name: 'Nigeria',
    flag: '🇳🇬',
    currencyCode: 'NGN',
    currencySymbol: '₦',
    currencyName: 'Nigerian Naira (NGN)',
    currencyPosition: 'before',
    numberFormat: 'standard',
    defaultTaxRate: 7.5,
    taxName: 'VAT',
  },
  {
    id: 'BR',
    name: 'Brazil',
    flag: '🇧🇷',
    currencyCode: 'BRL',
    currencySymbol: 'R$ ',
    currencyName: 'Brazilian Real (BRL)',
    currencyPosition: 'before',
    numberFormat: 'standard',
    defaultTaxRate: 17,
    taxName: 'ICMS',
  },
  {
    id: 'CUSTOM',
    name: 'Custom / Other',
    flag: '🌐',
    currencyCode: 'CUR',
    currencySymbol: '¤',
    currencyName: 'Custom Currency',
    currencyPosition: 'before',
    numberFormat: 'standard',
    defaultTaxRate: 0,
    taxName: 'Tax',
  }
];

export const getCountryPreset = (countryCodeOrId?: string): CountryCurrencyPreset => {
  if (!countryCodeOrId) return COUNTRY_CURRENCY_PRESETS[0]; // Default India/Rupee or US/Dollar
  return (
    COUNTRY_CURRENCY_PRESETS.find(
      c => c.id.toLowerCase() === countryCodeOrId.toLowerCase() ||
           c.currencyCode.toLowerCase() === countryCodeOrId.toLowerCase()
    ) || COUNTRY_CURRENCY_PRESETS[0]
  );
};
